services:
  tena_dcms:
    environment:
      - RAILS_ENV=development
    build:
      context: ./tena_dcms
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./tena_dcms:/app
      - db_data:/storage
    ports:
      - "3000:3000"

  tena_patients:
    environment:
      - RAILS_ENV=development
    build:
      context: ./tena_patients
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./tena_patients:/app
      - db_data:/storage
    ports:
      - "3001:3000"
    depends_on:
      - tena_dcms
  tena_appointments:
    environment:
      - RAILS_ENV=development
    build:
      context: ./tena_appointments
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./tena_appointments:/app
      - db_data:/storage
    ports:
      - "3002:3000"
    depends_on:
      - tena_dcms
  tena_laboratory:
    environment:
      - RAILS_ENV=development
    build:
      context: ./tena_laboratory
      dockerfile: Dockerfile
    command: bundle exec rails s -b 0.0.0.0
    volumes:
      - ./tena_laboratory:/app
      - db_data:/storage
    ports:
      - "3003:3000"
    depends_on:
      - tena_dcms

volumes:
  db_data:
