default: &default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: <%= ENV['DATABASE_PATH'] || '/storage/development.sqlite3' %>

development:
  <<: *default

test:
  <<: *default
  database: /storage/test.sqlite3

production:
  <<: *default
  database: /storage/production.sqlite3
